#ifndef _NATIVE_UI_INPUT_EVENT_H_
#define _NATIVE_UI_INPUT_EVENT_H_ 1

// External Dependencies
#include "../../core/include/types.h"

namespace native
{
    namespace ui
    {
        // Forward Declarations
        struct ComponentEvent;

        /**
            Comprises all of the available information about an input event for
            a Component. Input events are generated by mouse or touch actions,
            such pressing or releasing the mouse or touch on the Component, or
            swiping in a motion over the Component.
         */
        struct InputEvent
        {
            /** Actions which can be performed. */
            enum Action {
                Press			= 1,
                Release,
                Motion,
                Click,
                ContextClick,
				Enter,
				Leave
            };

            /** Devices or buttons which trigger the action. */
            enum Source {
                Mouse			= 0,	///< For Motion, Enter and Leave actions.
                LeftButton,				///< For `Press` or `Release` actions.
                MiddleButton,			///< For `Press` or `Release` actions.
                RightButton,			///< For `Press` or `Release` actions.
                BackButton,				///< For `Press` or `Release` actions.
                ForwardButton,			///< For `Press` or `Release` actions.
                Touch
            };

            // Instance Variables
            Action action;
            Source source;
            coord_t x;
            coord_t y;
            ComponentEvent* nativeEvent;
        };
    }
}

#endif // _NATIVE_UI_INPUT_EVENT_H_

