#ifndef _NATIVE_CORE_H_
#define _NATIVE_CORE_H_ 1

#include "../src/core/include/array.h"
#include "../src/core/include/asciicodec.h"
#include "../src/core/include/atomic.h"
#include "../src/core/include/clock.h"
#include "../src/core/include/collection.h"
#include "../src/core/include/convert.h"
#include "../src/core/include/exception.h"
#include "../src/core/include/flags.h"
#include "../src/core/include/function.h"
#include "../src/core/include/hash.h"
#include "../src/core/include/iterator.h"
#include "../src/core/include/latin1codec.h"
#include "../src/core/include/linkedlist.h"
#include "../src/core/include/list.h"
#include "../src/core/include/map.h"
#include "../src/core/include/math.h"
#include "../src/core/include/memory.h"
#include "../src/core/include/platform.h"
#include "../src/core/include/queue.h"
#include "../src/core/include/set.h"
#include "../src/core/include/shared.h"
#include "../src/core/include/signal.h"
#include "../src/core/include/singleton.h"
#include "../src/core/include/spinlock.h"
#include "../src/core/include/stack.h"
#include "../src/core/include/string.h"
#include "../src/core/include/stringcodec.h"
#include "../src/core/include/system.h"
#include "../src/core/include/task.h"
#include "../src/core/include/thread.h"
#include "../src/core/include/types.h"
#include "../src/core/include/utf8codec.h"

#endif // _NATIVE_CORE_H_

